# Generated by Django 4.1.7 on 2023-03-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20230301_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher_performance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
